/*
 * Copyright 2018 Valiantsin Kavalenka
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package stincmale.idenator;

import stincmale.idenator.doc.NotThreadSafe;

/**
 * A <i>hi</i> value generator for {@link AbstractHiLoLongIdGenerator}.
 * <p>
 * <i>hi</i> value must be unique, but we must specify the scope in which uniqueness is guaranteed:
 * each invocation of {@link #nextHi()} method on the same {@link HiValueGenerator} instance must produce a unique value
 * among all values generated by this instance.
 * Some implementations may provide a stronger guarantee (which should be explicitly specified),
 * e.g. by saying that each invocation of this method on different objects (even created in different runtimes)
 * must produce a unique value given that the objects were constructed the same way. Such implementations are called <i>persistent</i>.
 * <p>
 * Implementations may choose to be <i>strictly increasing</i>, <i>strictly decreasing</i> or <i>non-monotonic</i>.
 * Implementations may choose to generate <i>consecutive</i> or <i>non-consecutive</i> identifiers.
 */
@NotThreadSafe
public interface HiValueGenerator {
  /**
   * Generates the next <i>hi</i> value and returns it.
   * In practical cases the next value from a database sequence may be returned, making the implementation persistent.
   *
   * @return The next <i>hi</i> value, which must not be equal to {@link AbstractHiLoLongIdGenerator#UNINITIALIZED}.
   */
  long nextHi();
}
