/*
 * Copyright 2018 Valiantsin Kavalenka
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package stincmale.idenator;

/**
 * A generator of long identifiers.
 */
public interface LongIdGenerator {
  /**
   * Generates an identifier.
   * Word "identifier" implies uniqueness, but we must specify the scope in which uniqueness is guaranteed:
   * each invocation of this method on the same {@link LongIdGenerator} instance must produce a unique identifier
   * among all identifiers generated by this instance.
   * <p>
   * Some implementations may provide a stronger guarantee (which should be explicitly specified),
   * e.g. by saying that each invocation of this method on different objects (even created in different runtimes)
   * must produce a unique identifier given that the objects were constructed the same way. Such implementations are called persistent.
   *
   * @return A newly generated identifier.
   */
  long generate();
}
